import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/component/layout/Header";
import Footer from "@/component/layout/Footer";
import Navigation from "@/component/layout/Navigation";
import { Suspense } from "react";
import Alert from "@/component/layout/ui/Alert";
import Snackbar from "@/component/layout/ui/Snackbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
      <body className={inter.className}>
        {/* <Header /> */}

        <section>
          <Navigation />

          <article>
            {children}
          </article>
        </section>

        <Snackbar />
        {/* <Alert message="test" /> */}

        {/* <Footer /> */}
      </body>
    </html>
  );
}
